standart_c++ = -std=c++11
#debug = -DDEBUG
#tests = -DTESTS

LFU: main.cpp
	g++ main.cpp $(standart_c++) -DLFU $(debug) $(tests) -o out/LFU

LRU: main.cpp
	g++ main.cpp $(standart_c++) -DLRU $(debug) $(tests) -o out/LRU